export const FETCH_ARTISTS = 'FETCH_ARTISTS'
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS'
export const FETCH_ARTISTS_FAIL = 'FETCH_ARTISTS_FAIL'
export const UPDATE_QUERY = 'UPDATE_QUERY'